name: Ethereum Tests

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches: [ main, "release/**", "scroll-evm-executor/**" ]
  pull_request:
    branches: [ main, "release/**", "scroll-evm-executor/**" ]

jobs:
  tests-stable:
    name: Ethereum Tests (Stable)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        profile: [ ethtests, release ]
        target: [ i686-unknown-linux-gnu, x86_64-unknown-linux-gnu ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout ethereum/tests
        uses: actions/checkout@v4
        with:
          repository: ethereum/tests
          path: ethtests
          submodules: recursive
          ref: 66cb421ab8460f04f7cf2fee2818bcf8784ff5e2

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install cross
        run: cargo install cross

      - name: Run Ethereum tests
        run: |
          cross run --target ${{matrix.target}} --profile ${{ matrix.profile }} -p revme -- statetest \
            ethtests/GeneralStateTests/ \
            ethtests/LegacyTests/Constantinople/GeneralStateTests/ \
            ethtests/EIPTests/StateTests/stEIP1153-transientStorage/ \
            ethtests/EIPTests/StateTests/stEIP4844-blobtransactions/ \
            ethtests/EIPTests/StateTests/stEIP2537/ \
            tests/eof_suite/eest/state_tests \
            tests/prague_suite/state_tests
      - name: Run EOF validation tests
        run: |
          cross run --target ${{matrix.target}} --profile ${{ matrix.profile }} -p revme -- eof-validation \
          tests/eof_suite/eest/eof_tests/osaka

